-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."plan" add column "number_of_applicants" integer
--  not null default '50';
