import Head from "next/head";
import styles from "../styles/Home.module.css";
import React from "react";
import { useAuthContext } from "../context/AuthContext";

export default function Home() {
  const { user } = useAuthContext();

  console.log("Home", user);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <p>Hello</p>
      </div>
    </div>
  );
}
