import Head from "next/head";
import React, { VFC } from "react";
import HomePage from "../components/pages/home/Home";

const Home: VFC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  );
};

export default Home;
