import Head from "next/head";
import React, { VFC } from "react";
import { useAuthContext } from "../context/AuthContext";
import { usePrivatePage } from "../hooks/usePrivatePage";
import { Box, Heading, Spinner } from "@chakra-ui/react";
import { SidebarTemplate } from "../components/templates/sidebar-template/SidebarTemplate";

const Home: VFC = () => {
  const { loading } = usePrivatePage();
  const { user } = useAuthContext();

  if (loading) {
    return <Spinner />;
  }

  return (
    <SidebarTemplate>
      <Box flex="1">
        <Heading as="h1">トップ</Heading>
        <div>Name: {user?.name}</div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div>
          <p>Hello</p>
        </div>
      </Box>
    </SidebarTemplate>
  );
};

export default Home;
