-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."community" add column "thumbnail_url" text
--  not null default 'https://example.com';
