name: Server

on:
  pull_request:
    paths:
      - "server/**"
      - "!**.md"
      - "!.editorconfig"
      - "!.gitignore"
      - "!.gitattributes"


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: package Install
        run: yarn install
        working-directory: ./server
      - name: copy dotenv
        run: cp .env.ci .env
        working-directory: ./server
      - name: docker
        run: docker-compose up -d
      # - name: migrate db
      #   run: yarn run migrate
      #   working-directory: ./server
      - name: check type
        run: yarn run check-types
        working-directory: ./server
      - name: test
        run: yarn run test
        working-directory: ./server
